### ISSUE TITLE
Use Python 3

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#8]
As discussed in the group meeting, we should use Python 3 for our code. To start porting, just try to run it with the `python3` interpreter instead of the 2.7 one and fix the errors.

**Comment by rickmcgeer** [comment]
Need to check into whether the Google App Engine really supports Python 3 in the standard environment.  it does in the flex environment.  https://cloud.google.com/appengine/docs/flexible/python/runtime

**Comment by aaaaalbert** [comment]
First error encountered:
```
albertra@node-0:~/sundew-one/daemons$ flask --version
Flask 1.0.2
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
albertra@node-0:~/sundew-one/daemons$ export FLASK_APP=user_daemon.py 
albertra@node-0:~/sundew-one/daemons$ export FLASK_ENV=development
albertra@node-0:~/sundew-one/daemons$ flask run
 * Serving Flask app "user_daemon.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/users/albertra/sundew-one/daemons/user_daemon.py", line 33
    log(cmd)
           ^
TabError: inconsistent use of tabs and spaces in indentation
albertra@node-0:~/sundew-one/daemons$ 
```

Don't mix tabs and spaces please!

**Comment by aaaaalbert** [comment]
Fixed that one in 0d457cdbf47654ad03794a93c4547330c4e7f9f0.

**Comment by aaaaalbert** [comment]
Now Flask basically runs (given its dependencies are installed, see #2).

Next error:
```
[log]: ['../user_files/scripts/make-config.sh', 'default', '-n', None]
[2018-05-24 07:47:21,956] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/users/albertra/sundew-one/daemons/user_daemon.py", line 34, in hello
    log('request for user: ' + user)
TypeError: Can't convert 'NoneType' object to str implicitly
127.0.0.1 - - [24/May/2018 07:47:21] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [24/May/2018 07:47:22] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [24/May/2018 07:47:22] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by aaaaalbert** [comment]
By the way, I'm testing with the Flask development server on `localhost` on my GENI node and SSH:
```
albert$ ssh -i .ssh/..... albertra@pcvm1-3.instageni.ucsd.edu -L 8080:localhost:5000
```

**Comment by aaaaalbert** [comment]
Supplying a `user` argument to the server, we have an actual Python2/3 compatibility problem with `unicode` I guess:
```
127.0.0.1 - - [24/May/2018 07:53:15] "GET / HTTP/1.1" 500 -
[log]: ['../user_files/scripts/make-config.sh', 'default', '-n', 'albert']
[log]: request for user: albert
serviceaccounts "default" not found.
[2018-05-24 07:53:47,969] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/users/albertra/sundew-one/daemons/user_daemon.py", line 35, in hello
    result = make_call(cmd)
  File "/users/albertra/sundew-one/daemons/user_daemon.py", line 22, in make_call
    f.write((unicode(result[0],"utf-8")))
NameError: name 'unicode' is not defined
127.0.0.1 - - [24/May/2018 07:53:47] "GET /?user=albert HTTP/1.1" 500 -
```

**Comment by aaaaalbert** [comment]
@rickmcgeer reports that yes, Google App Engine does support Python 3.
